-- MySQL Script generated by MySQL Workbench
-- Sun Apr  3 21:46:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`character` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `age` INT(2) NULL,
  `weight` DOUBLE NULL,
  `history` VARCHAR(256) NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(70) NOT NULL,
  `title` VARCHAR(70) NOT NULL,
  `release_date` DATE NOT NULL,
  `score` INT(1) NOT NULL,
  `genreId` INT NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`, `genreId`),
  INDEX `fk_movie_genre1_idx` (`genreId` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  CONSTRAINT `fk_movie_genre1`
    FOREIGN KEY (`genreId`)
    REFERENCES `mydb`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`charactermovies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`charactermovies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `characterId` INT NOT NULL,
  `movieId` INT NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  PRIMARY KEY (`id`, `movieId`, `characterId`),
  INDEX `fk_character_has_movie_movie1_idx` (`movieId` ASC) VISIBLE,
  INDEX `fk_character_has_movie_character1_idx` (`characterId` ASC) VISIBLE,
  CONSTRAINT `fk_character_has_movie_character1`
    FOREIGN KEY (`characterId`)
    REFERENCES `mydb`.`character` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_has_movie_movie1`
    FOREIGN KEY (`movieId`)
    REFERENCES `mydb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `userId` INT NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
